CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users  
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
INSERT INTO telegram_users VALUES (?,?,?,?,?)
"""

CREATE_VOICE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS poll_votes (
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
ANSWER TEXT,
UNIQUE (ID))
"""

INSERT_VOICE_QUERY = """
INSERT INTO poll_votes(TELEGRAM_ID, ANSWER) VALUES (?,?)
"""

CREATE_BAN_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS ban_list  
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
COUNT INTEGER,
UNIQUE (TELEGRAM_ID)
)
"""
INSERT_BAN_USER_QUERY = """
INSERT OR IGNORE INTO ban_list VALUES (?,?,?)
"""

SELECT_BAN_USERS_QUERY = """
SELECT * FROM ban_list WHERE TELEGRAM_ID = ?
"""

UPDATE_BAN_USER_COUNT_QUERY = """
UPDATE ban_list SET COUNT = COUNT + 1 WHERE TELEGRAM_ID = ?
"""
